environment:
  matrix:
    -
      job_group: tests
      APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu2004
      PYTHON: '3.8'
  GIT_TOKEN:
    secure: +jQhxLpePj6hdDryfET/XpLo7VL9fhDXVHlwLOPp/nRDYe97TJAfd0XCTuPz1qkT

stack: python %PYTHON%
build: off
skip_tags: true

for:
  -
    matrix:
      only:
        - job_group: tests
    install:
      - git submodule update --init --recursive
      # GNU/Linux build config
      - sh: 'lsb_release -a'
      - sh: 'export extras_pkg="linux-*-extra-$(uname -r)"'
      - sh: 'sudo apt-get install -y $extras_pkg'
      # MS Windows build config
      - cmd: 'systeminfo'
      - cmd: 'set PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%'
    test_script:
      - sh:  './test.sh'
      - cmd: 'powershell .\test.ps1'
